# SPDX-License-Identifier: LGPL-2.1-or-later
# Every action in .github/workflows is pinned by commit; this is what moves
# those pins when a new release of the action appears.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
