// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

import Testing
import Foundation
@testable import LibreMacAgentClient

// Cross-implementation fixtures: `Fixtures/*.cbor` are canonical FRAME BODY
// bytes (no 8-byte frame header) generated by the LibreDarwin agent's own
// C++ encoder — `agent/tests/MessagesRoundTripTest.cpp --dump-fixtures
// <dir>`, run against a real build of `LibreSCRS::Darwin::wire` — covering
// one instance of every reply/event shape, including the op-path shapes
// (OpProgress/OpResultReady/OpFinished) the card-free smoke tests cannot
// reach. Decoding every file here with THIS package's parser is the
// cross-implementation contract check: two independent encoders (Swift
// hand-written fixtures in MessagesRoundTripTests.swift; C++ QCBOR-backed
// encoder here) must agree byte-for-byte with one decoder.
//
// To regenerate: LibreDarwin `cmake --build build-release -j4 --target
// MessagesRoundTripTest && ./build-release/agent/tests/MessagesRoundTripTest
// --dump-fixtures <dir>`, then copy `<dir>/*.cbor` over this directory.

private func fixture(_ name: String) throws -> Data {
    let url = try #require(Bundle.module.url(forResource: name, withExtension: "cbor", subdirectory: "Fixtures"))
    return try Data(contentsOf: url)
}

private let sampleCertInfo = CertificateInfo(
    certId: "deadbeef",
    signingCapable: true,
    fields: ["Subject": ["CN": CertField(labelKey: "cn.subject.key", labelFallback: "Common Name", value: "John Doe")]],
    keyUsageBits: 1,
    ekus: ["clientAuth"],
    chainSubjectCns: ["Root CA"],
    trustStatus: 0)

@Suite("Cross-implementation fixtures (generated by the LibreDarwin C++ encoder)")
struct CrossImplementationFixtureTests {

    // ---- replies ----

    @Test("HelloAck.cbor")
    func helloAck() throws {
        let env = try AgentMessages.decodeReply(try fixture("HelloAck"))
        #expect(env.req == 1)
        #expect(env.reply == .helloAck(agentVer: "0.1.0", features: ["pki", "sign"]))
    }

    @Test("OpStarted.cbor")
    func opStarted() throws {
        let env = try AgentMessages.decodeReply(try fixture("OpStarted"))
        #expect(env.req == 2)
        #expect(env.reply == .opStarted(op: 42))
    }

    @Test("State.cbor")
    func state() throws {
        let env = try AgentMessages.decodeReply(try fixture("State"))
        #expect(env.req == 3)
        #expect(
            env.reply
                == .state(
                    readers: [ReaderState(handle: "r1", name: "Reader One", hasCard: true, card: "c1")],
                    cards: [CardState(handle: "c1", reader: "r1", caps: Capabilities(rawValue: 3), preAuth: .paceCan)]
                ))
    }

    @Test("CertList.cbor")
    func certList() throws {
        let env = try AgentMessages.decodeReply(try fixture("CertList"))
        #expect(env.req == 4)
        #expect(env.reply == .certList(certs: [sampleCertInfo]))
    }

    @Test("CertDer.cbor")
    func certDer() throws {
        let env = try AgentMessages.decodeReply(try fixture("CertDer"))
        #expect(env.req == 5)
        #expect(env.reply == .certDer(der: Data([0xDE, 0xAD, 0xBE, 0xEF])))
    }

    @Test("Config.cbor")
    func config() throws {
        let env = try AgentMessages.decodeReply(try fixture("Config"))
        #expect(env.req == 6)
        #expect(env.reply == .config(entries: ["DefaultLevel": .text("b-t")]))
    }

    @Test("Ack.cbor")
    func ack() throws {
        let env = try AgentMessages.decodeReply(try fixture("Ack"))
        #expect(env.req == 7)
        #expect(env.reply == .ack)
    }

    @Test("SignRecovery.cbor")
    func signRecovery() throws {
        let env = try AgentMessages.decodeReply(try fixture("SignRecovery"))
        #expect(env.req == 8)
        #expect(
            env.reply
                == .signRecovery(SignResult(artifact: 5, meta: SignMeta(format: "pades", level: "b-lta", tsaUsed: true, chainComplete: true))))
    }

    @Test("ErrCode.cbor — numeric `code` arm")
    func errCode() throws {
        let env = try AgentMessages.decodeReply(try fixture("ErrCode"))
        #expect(env.req == 9)
        #expect(env.reply == .err(ErrInfo(code: .code(.cardRemoved), msgKey: "cardRemoved", msgFallback: "Card removed")))
    }

    @Test("ErrName.cbor — named `name` arm, no msgKey/msgFallback")
    func errName() throws {
        let env = try AgentMessages.decodeReply(try fixture("ErrName"))
        #expect(env.req == 10)
        #expect(env.reply == .err(ErrInfo(code: .name(.unknownCard))))
    }

    // ---- events ----

    @Test("ReaderAdded.cbor")
    func readerAdded() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("ReaderAdded"))
        #expect(ev == .readerAdded(ReaderState(handle: "r1", name: "Reader One", hasCard: false)))
    }

    @Test("ReaderRemoved.cbor")
    func readerRemoved() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("ReaderRemoved"))
        #expect(ev == .readerRemoved(handle: "r1"))
    }

    @Test("CardAdded.cbor")
    func cardAdded() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("CardAdded"))
        #expect(ev == .cardAdded(CardState(handle: "c1", reader: "r1", caps: Capabilities(rawValue: 3), preAuth: .paceCan)))
    }

    @Test("CardRemoved.cbor")
    func cardRemoved() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("CardRemoved"))
        #expect(ev == .cardRemoved(handle: "c1"))
    }

    @Test("PropertyChanged.cbor")
    func propertyChanged() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("PropertyChanged"))
        #expect(ev == .propertyChanged(handle: "r1", iface: "org.librescrs.Reader1", props: ["hasCard": .bool(true)]))
    }

    @Test("ConfigChanged.cbor")
    func configChanged() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("ConfigChanged"))
        #expect(ev == .configChanged(key: "DefaultLevel"))
    }

    @Test("OpProgress.cbor — fractional progress (0.5) round-trips as f16")
    func opProgress() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpProgress"))
        #expect(ev == .opProgress(op: 9, phase: .signing, progress: 0.5, indeterminate: nil, watchdogSecs: nil))
        if case .opProgress(_, _, let progress, _, _) = ev {
            #expect(progress == 0.5)
        }
    }

    @Test("OpResultReadyIdentity.cbor")
    func opResultReadyIdentity() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyIdentity"))
        #expect(
            ev
                == .opResultReady(
                    op: 20,
                    result: .identity(
                        IdentityResult(fields: [
                            "MRZ": ["Name": IdentityField(labelKey: "name.key", labelFallback: "Name", type: "text", value: .text("JOHN DOE"))]
                        ]))
                ))
    }

    @Test("OpResultReadyPhoto.cbor")
    func opResultReadyPhoto() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyPhoto"))
        #expect(ev == .opResultReady(op: 21, result: .photo(PhotoResult(photos: [PhotoItem(key: "MRZ:Photo", fd: 0)]))))
    }

    @Test("OpResultReadyCertificates.cbor")
    func opResultReadyCertificates() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyCertificates"))
        #expect(ev == .opResultReady(op: 22, result: .certificates([sampleCertInfo])))
    }

    @Test("OpResultReadySign.cbor — fd index, never inline bytes")
    func opResultReadySign() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadySign"))
        #expect(
            ev
                == .opResultReady(
                    op: 23,
                    result: .sign(SignResult(artifact: 5, meta: SignMeta(format: "pades", level: "b-lta", tsaUsed: true, chainComplete: true)))
                ))
    }

    @Test("OpFinished.cbor")
    func opFinished() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpFinished"))
        #expect(ev == .opFinished(op: 24, status: .error, code: .cardRemoved, msgKey: "op.failed", msgFallback: "Card removed"))
    }

    @Test("AgentQuiesced.cbor")
    func agentQuiesced() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("AgentQuiesced"))
        #expect(ev == .agentQuiesced(reason: .screenLocked))
    }

    // ---- coverage guard: every fixture file gets a decode attempt above ----

    @Test("every checked-in fixture file is exercised by name above")
    func everyFixtureIsCovered() throws {
        let dir = try #require(Bundle.module.url(forResource: "Fixtures", withExtension: nil))
        let files = try FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil)
        let names = Set(files.map { $0.deletingPathExtension().lastPathComponent })
        let covered: Set<String> = [
            "HelloAck", "OpStarted", "State", "CertList", "CertDer", "Config", "Ack", "SignRecovery", "ErrCode",
            "ErrName", "ReaderAdded", "ReaderRemoved", "CardAdded", "CardRemoved", "PropertyChanged",
            "ConfigChanged", "OpProgress", "OpResultReadyIdentity", "OpResultReadyPhoto",
            "OpResultReadyCertificates", "OpResultReadySign", "OpFinished", "AgentQuiesced",
        ]
        #expect(names == covered)
    }
}
