// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2026 hirashix0

import Testing
import Foundation
@testable import LibreMacAgentClient

// Cross-implementation fixtures: `Fixtures/*.cbor` are canonical FRAME BODY
// bytes (no 8-byte frame header) generated by LibreAgent's own C++ encoder —
// `tests/wire/MessagesRoundTripTest --dump-fixtures <dir>`, run against a
// real build of `LibreSCRS::Agent::Wire` — covering one instance of every
// reply/event shape, including the op-path shapes (OpProgress/OpResultReady/
// OpFinished) the card-free smoke tests cannot reach. Decoding every file
// here with THIS package's parser is the cross-implementation contract
// check: two independent encoders (Swift hand-written fixtures in
// MessagesRoundTripTests.swift; C++ QCBOR-backed encoder here) must agree
// byte-for-byte with one decoder.
//
// The REQUEST fixtures (client -> agent shapes) invert that: the C++ agent
// is the decoder there, so those tests byte-compare THIS package's
// `AgentRequest.encode(req: 1)` output against the C++ generator's bytes
// (the generator hardcodes req id 1) — both sides emit canonical CBOR, so
// equality is exact.
//
// To regenerate: LibreAgent build: `cmake --build <build-dir> -j4 --target
// MessagesRoundTripTest && <build-dir>/tests/wire/MessagesRoundTripTest
// --dump-fixtures <dir>`, then copy `<dir>/*.cbor` over this directory.

private func fixture(_ name: String) throws -> Data {
    let url = try #require(Bundle.module.url(forResource: name, withExtension: "cbor", subdirectory: "Fixtures"))
    return try Data(contentsOf: url)
}

private let sampleCertInfo = CertificateInfo(
    certId: "deadbeef",
    signingCapable: true,
    fields: ["Subject": ["CN": CertField(labelKey: "cn.subject.key", labelFallback: "Common Name", value: "John Doe")]],
    keyUsageBits: 1,
    ekus: ["clientAuth"],
    chainSubjectCns: ["Root CA"],
    trustStatus: 0)

@Suite("Cross-implementation fixtures (generated by the LibreAgent C++ encoder)")
struct CrossImplementationFixtureTests {

    // ---- replies ----

    @Test("HelloAck.cbor")
    func helloAck() throws {
        let env = try AgentMessages.decodeReply(try fixture("HelloAck"))
        #expect(env.req == 1)
        #expect(env.reply == .helloAck(agentVer: "0.1.0", features: ["pki", "sign"]))
    }

    @Test("OpStarted.cbor")
    func opStarted() throws {
        let env = try AgentMessages.decodeReply(try fixture("OpStarted"))
        #expect(env.req == 2)
        #expect(env.reply == .opStarted(op: 42))
    }

    @Test("State.cbor")
    func state() throws {
        let env = try AgentMessages.decodeReply(try fixture("State"))
        #expect(env.req == 3)
        #expect(
            env.reply
                == .state(
                    readers: [ReaderState(handle: "r1", name: "Reader One", hasCard: true, card: "c1")],
                    cards: [CardState(handle: "c1", reader: "r1", caps: Capabilities(rawValue: 3), preAuth: .can)]
                ))
    }

    @Test("CertList.cbor")
    func certList() throws {
        let env = try AgentMessages.decodeReply(try fixture("CertList"))
        #expect(env.req == 4)
        #expect(env.reply == .certList(certs: [sampleCertInfo]))
    }

    @Test("CertDer.cbor")
    func certDer() throws {
        let env = try AgentMessages.decodeReply(try fixture("CertDer"))
        #expect(env.req == 5)
        #expect(env.reply == .certDer(der: Data([0xDE, 0xAD, 0xBE, 0xEF])))
    }

    @Test("Config.cbor")
    func config() throws {
        let env = try AgentMessages.decodeReply(try fixture("Config"))
        #expect(env.req == 6)
        #expect(env.reply == .config(entries: ["DefaultLevel": .text("b-t")]))
    }

    @Test("Ack.cbor")
    func ack() throws {
        let env = try AgentMessages.decodeReply(try fixture("Ack"))
        #expect(env.req == 7)
        #expect(env.reply == .ack)
    }

    @Test("SignRecovery.cbor")
    func signRecovery() throws {
        let env = try AgentMessages.decodeReply(try fixture("SignRecovery"))
        #expect(env.req == 8)
        #expect(
            env.reply
                == .signRecovery(SignResult(artifact: 5, meta: SignMeta(format: "pades", level: "b-lta", tsaUsed: true, chainComplete: true))))
    }

    @Test("ErrCode.cbor — numeric `code` arm")
    func errCode() throws {
        let env = try AgentMessages.decodeReply(try fixture("ErrCode"))
        #expect(env.req == 9)
        #expect(env.reply == .err(ErrInfo(code: .code(.cardRemoved), msgKey: "cardRemoved", msgFallback: "Card removed")))
    }

    @Test("ErrName.cbor — named `name` arm, no msgKey/msgFallback")
    func errName() throws {
        let env = try AgentMessages.decodeReply(try fixture("ErrName"))
        #expect(env.req == 10)
        #expect(env.reply == .err(ErrInfo(code: .name(.unknownCard))))
    }

    @Test("ErrNameUnknownCredential.cbor — named `name` arm, UnknownCredential")
    func errNameUnknownCredential() throws {
        let env = try AgentMessages.decodeReply(try fixture("ErrNameUnknownCredential"))
        #expect(env.req == 11)
        #expect(env.reply == .err(ErrInfo(code: .name(.unknownCredential))))
    }

    @Test("ErrNameNoResult.cbor — named `name` arm, GetSignResult's dedicated missing-result name")
    func errNameNoResult() throws {
        let env = try AgentMessages.decodeReply(try fixture("ErrNameNoResult"))
        #expect(env.req == 14)
        #expect(env.reply == .err(ErrInfo(code: .name(.noResult))))
    }

    // ---- Unknown-reply-arm tolerance ----
    //
    // Layout.cbor / AppearanceFont.cbor are the `Manager1.LayoutVisualSignature`
    // / `GetAppearanceFont` reply arms — real, byte-exact new arms the C++ agent
    // now serves, generated by the SAME `--dump-fixtures` tool as every fixture
    // above. This Swift client has no layout API (the Qt client is the only
    // consumer for now) and `AgentMessages.decodeReply` was never taught
    // either arm's shape, so both must fall through its existing
    // no-known-key-matched path and throw `.unrecognizedShape` — never crash,
    // never hang, never silently mis-decode as some OTHER arm. This is the
    // forward-compatibility tolerance contract (a genuinely new agent
    // capability must not disturb an older client) exercised against a REAL
    // new wire arm for the first time, rather than a hand-rolled
    // malformed-frame stand-in. Both of `decodeReply`'s
    // two production callers swallow this via `try?` (`AgentClient.swift:337`,
    // `TokenAgentClient.swift:60`), so in practice the effect is "the pending
    // call times out on its own existing budget" — skip, not crash.
    @Test("Layout.cbor — a new reply arm this client build does not know decodes to unrecognizedShape, not a crash")
    func layoutArmDoesNotDisturbAnOlderClient() throws {
        let bytes = try fixture("Layout")
        #expect(throws: MessageError.unrecognizedShape) {
            try AgentMessages.decodeReply(bytes)
        }
    }

    @Test("AppearanceFont.cbor — ditto for the sibling fd-carrying new arm")
    func appearanceFontArmDoesNotDisturbAnOlderClient() throws {
        let bytes = try fixture("AppearanceFont")
        #expect(throws: MessageError.unrecognizedShape) {
            try AgentMessages.decodeReply(bytes)
        }
    }

    // Progressive per-group identity delivery ("OpIdentityGroup") is a genuinely
    // new EVENT `t` this client build has never heard of — the event-side twin
    // of the Layout/AppearanceFont reply-arm tolerance above, but through
    // `decodeEvent`'s OWN forward-compatibility path rather than `decodeReply`'s:
    // an unrecognized `t` there throws `.unknownMessage` (not `.unrecognizedShape`
    // — the two decoders use different sentinel errors for the same "shape I
    // don't know" situation; see `decodeEvent`'s own doc comment in
    // Messages.swift), which is skipped/ignored by every production event-dispatch
    // call site, never a crash or a dropped connection. Proves an OLD Swift
    // client build tolerates a NEWER agent that streams progressive groups.
    @Test("OpIdentityGroup.cbor — a new event this client build does not know is skipped, not a crash")
    func opIdentityGroupEventDoesNotDisturbAnOlderClient() throws {
        let bytes = try fixture("OpIdentityGroup")
        #expect(throws: MessageError.unknownMessage) {
            try AgentMessages.decodeEvent(bytes)
        }
    }

    // OpResultReadySignBatch.cbor exercises a DIFFERENT tolerance seam than
    // the three above: the outer event tag is "OpResultReady", a shape this
    // client already knows, but its nested `result.kind` is "SignBatch" — a
    // genuinely new op-result kind this client build has no case for (batch
    // signing has no Swift client API yet; that lands with the client-facing
    // surface in a later task). `parseOpResult`'s exhaustive `switch` on
    // `kind` already has a `default: throw .wrongType("kind")` branch
    // (Messages.swift), so an unrecognised nested kind is structurally
    // guaranteed to degrade to a clean typed error rather than crash or
    // mis-decode as some OTHER result — this is the SAME "skip, not crash"
    // guarantee as the reply-arm/event-tag cases above, proven here against
    // a real, byte-exact new result shape for the first time. Both of
    // `decodeEvent`'s production callers swallow this the same way they
    // swallow `.unknownMessage`/`.unrecognizedShape`.
    @Test("OpResultReadySignBatch.cbor — a new op-result kind this client build does not know decodes to wrongType, not a crash")
    func opResultReadySignBatchKindDoesNotDisturbAnOlderClient() throws {
        let bytes = try fixture("OpResultReadySignBatch")
        #expect(throws: MessageError.wrongType("kind")) {
            try AgentMessages.decodeEvent(bytes)
        }
    }

    // ---- requests (client -> agent: Swift encode vs the C++ bytes, req id 1) ----

    @Test("ReadTokenInfo.cbor — Swift encode matches the C++ bytes")
    func readTokenInfoRequest() throws {
        let expected = try fixture("ReadTokenInfo")
        #expect(AgentRequest.readTokenInfo(card: "reader/0:card/0").encode(req: 1) == expected)
    }

    @Test("ListCredentials.cbor — Swift encode matches the C++ bytes")
    func listCredentialsRequest() throws {
        let expected = try fixture("ListCredentials")
        #expect(AgentRequest.listCredentials(card: "reader/0:card/0").encode(req: 1) == expected)
    }

    @Test("ManagePin.cbor — Swift encode matches the C++ bytes; activateKey omitted for verb `change`")
    func managePinRequest() throws {
        let expected = try fixture("ManagePin")
        let encoded = AgentRequest.managePin(
            card: "reader/0:card/0", pinId: "sign:0x92", verb: .change, activateKey: false
        ).encode(req: 1)
        #expect(encoded == expected)
    }

    @Test("ActivateSigningKey.cbor — Swift encode matches the C++ bytes")
    func activateSigningKeyRequest() throws {
        let expected = try fixture("ActivateSigningKey")
        #expect(AgentRequest.activateSigningKey(card: "reader/0:card/0").encode(req: 1) == expected)
    }

    // ---- events ----

    @Test("ReaderAdded.cbor")
    func readerAdded() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("ReaderAdded"))
        #expect(ev == .readerAdded(ReaderState(handle: "r1", name: "Reader One", hasCard: false)))
    }

    @Test("ReaderRemoved.cbor")
    func readerRemoved() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("ReaderRemoved"))
        #expect(ev == .readerRemoved(handle: "r1"))
    }

    @Test("CardAdded.cbor")
    func cardAdded() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("CardAdded"))
        #expect(ev == .cardAdded(CardState(handle: "c1", reader: "r1", caps: Capabilities(rawValue: 3), preAuth: .can)))
    }

    @Test("CardRemoved.cbor")
    func cardRemoved() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("CardRemoved"))
        #expect(ev == .cardRemoved(handle: "c1"))
    }

    @Test("PropertyChanged.cbor")
    func propertyChanged() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("PropertyChanged"))
        #expect(ev == .propertyChanged(handle: "r1", iface: "org.librescrs.Reader1", props: ["hasCard": .bool(true)]))
    }

    @Test("ConfigChanged.cbor")
    func configChanged() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("ConfigChanged"))
        #expect(ev == .configChanged(key: "DefaultLevel"))
    }

    @Test("OpProgress.cbor — fractional progress (0.5) round-trips as f16")
    func opProgress() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpProgress"))
        #expect(ev == .opProgress(op: 9, phase: .signing, progress: 0.5, indeterminate: nil, watchdogSecs: nil))
        if case .opProgress(_, _, let progress, _, _) = ev {
            #expect(progress == 0.5)
        }
    }

    @Test("OpResultReadyIdentity.cbor")
    func opResultReadyIdentity() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyIdentity"))
        #expect(
            ev
                == .opResultReady(
                    op: 20,
                    result: .identity(
                        IdentityResult(fields: [
                            "MRZ": ["Name": IdentityField(labelKey: "name.key", labelFallback: "Name", type: "text", value: .text("JOHN DOE"))]
                        ]))
                ))
    }

    @Test("OpResultReadyPhoto.cbor")
    func opResultReadyPhoto() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyPhoto"))
        #expect(ev == .opResultReady(op: 21, result: .photo(PhotoResult(photos: [PhotoItem(key: "MRZ:Photo", fd: 0)]))))
    }

    @Test("OpResultReadyCertificates.cbor")
    func opResultReadyCertificates() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyCertificates"))
        #expect(ev == .opResultReady(op: 22, result: .certificates([sampleCertInfo])))
    }

    @Test("OpResultReadySign.cbor — fd index, never inline bytes")
    func opResultReadySign() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadySign"))
        #expect(
            ev
                == .opResultReady(
                    op: 23,
                    result: .sign(SignResult(artifact: 5, meta: SignMeta(format: "pades", level: "b-lta", tsaUsed: true, chainComplete: true)))
                ))
    }

    @Test("OpResultReadyCredentialsList.cbor — Ok listing, one fully-populated record (all 23 cred-record keys)")
    func opResultReadyCredentialsList() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyCredentialsList"))
        let record = CredentialRecord(
            id: "sign:0x92", label: "Signing PIN", kind: .sign, state: .operational,
            retriesLeft: 3, retriesMax: 3, usesLeft: 5, usesMax: 20, unblocksLeft: 10, minLength: 4, maxLength: 8,
            canChange: true, unblockable: true, unblockStyle: .unblockAndChange,
            activatable: true, keyActivationPending: true, keyActivatable: true,
            recovery: .holderViaPuk, probeSafe: true,
            blockedGuidanceKey: "guidance.blocked.key",
            blockedGuidanceFallback: "Blocked; contact issuer",
            keyActivationGuidanceKey: "guidance.activate.key",
            keyActivationGuidanceFallback: "Activate your signing key")
        #expect(
            ev
                == .opResultReady(
                    op: 25,
                    result: .credentials(
                        CredentialsPayload(
                            result: CredentialResult(outcome: .ok, blocked: false), records: [record]))
                ))
    }

    @Test("OpResultReadyCredentialsFailed.cbor — failed mutation: invalidPin, retriesLeft=2, no records")
    func opResultReadyCredentialsFailed() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpResultReadyCredentialsFailed"))
        #expect(
            ev
                == .opResultReady(
                    op: 26,
                    result: .credentials(
                        CredentialsPayload(
                            result: CredentialResult(outcome: .invalidPin, retriesLeft: 2, blocked: false),
                            records: []))
                ))
    }

    @Test("OpFinished.cbor")
    func opFinished() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("OpFinished"))
        #expect(ev == .opFinished(op: 24, status: .error, code: .cardRemoved, msgKey: "op.failed", msgFallback: "Card removed"))
    }

    @Test("AgentQuiesced.cbor")
    func agentQuiesced() throws {
        let ev = try AgentMessages.decodeEvent(try fixture("AgentQuiesced"))
        #expect(ev == .agentQuiesced(reason: .screenLocked))
    }

    // ---- coverage guard: every fixture file gets a decode attempt above ----

    @Test("every checked-in fixture file is exercised by name above")
    func everyFixtureIsCovered() throws {
        let dir = try #require(Bundle.module.url(forResource: "Fixtures", withExtension: nil))
        let files = try FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil)
        let names = Set(files.map { $0.deletingPathExtension().lastPathComponent })
        let covered: Set<String> = [
            "HelloAck", "OpStarted", "State", "CertList", "CertDer", "Config", "Ack", "SignRecovery", "ErrCode",
            "ErrName", "ErrNameUnknownCredential", "ErrNameNoResult", "ReadTokenInfo", "ListCredentials", "ManagePin",
            "ActivateSigningKey",
            "ReaderAdded", "ReaderRemoved", "CardAdded", "CardRemoved", "PropertyChanged",
            "ConfigChanged", "OpProgress", "OpResultReadyIdentity", "OpResultReadyPhoto",
            "OpResultReadyCertificates", "OpResultReadySign", "OpResultReadyCredentialsList",
            "OpResultReadyCredentialsFailed", "OpFinished", "AgentQuiesced",
            // Unknown-arm/unknown-event/unknown-nested-kind tolerance
            // fixtures: each has its OWN dedicated test above (asserting the
            // specific decode error), not a decoded-value assertion like
            // every entry above, but still "exercised by name" — included
            // here so this guard's `names == covered` actually holds against
            // every checked-in file (found drifted — Layout/AppearanceFont
            // were never added here despite their own tests already
            // existing — and fixed in the SAME task that added the third
            // member of this family, OpIdentityGroup).
            "Layout", "AppearanceFont", "OpIdentityGroup",
            // OpResultReadySignBatch: the nested-kind tolerance twin of the
            // three above (see its own test's comment) — added in the SAME
            // task that introduced the "SignBatch" op-result kind.
            "OpResultReadySignBatch",
        ]
        #expect(names == covered)
    }
}
